sudo: required
dist: bionic

language: php
php:
        - 7.3

addons:
        apt:
                packages:
                        - zlib1g-dev
                        - memcached

script:
         ./.travis/build.sh 
